server:
  port: 8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

spring:
  application:
    name: config-server

  profiles:
    active: native

  cloud:
    config:
       # 读取git的配置
#      server:
#        git:
#          uri: https://github.com/LinkinStars/SpringCloudTemplate
#          search-paths: SpringCloudConfig
#          default-label: master
#          username:
#          password:
#      fail-fast: true
      # 读取本地配置
      server:
        native:
          searchLocations: /Users/LinkinStar/IdeaProjects/SpringCloudTemplate/SpringCloudConfig/
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh